### PR TITLE
NLS & DYLC Dates

### PR DESCRIPTION
**Pull request by InfamousStarFox**

### CODE REVIEW

**Comment by blove** [comment]
@InfamousStarFox I believe we can remove the registration alert. Can you reach out to Rob to see if he has registration links set up for 2017?

**Comment by rjrosamond** [comment]
@blove @InfamousStarFox We don't have registration setup yet as I am still working on building the event budgets so that we can determine the the registration fees.  For right now, all we have are dates and locations:

May 5-7, 2017: NLS & DYLC - Salt Lake City, UT - Camp Tracy
October 6-8, 2017: NLS & DYLC - Portland, OR - Camp Kuratle at Trestle Glen
November 10-12, 2017: NLS only - Tokyo, Japan - Tama Hills Recreation Center

All of these dates are already loaded into the WR Google Calendar

**Comment by blove** [comment]
Thank you @rjrosamond 

@InfamousStarFox let's change the alert to indicate that the registration links will be available when we are closer to the event. Also, I think we are missing the Tokyo dates. Please add that info as well.

**Comment by InfamousStarFox** [comment]
@blove I have updated the registration alert to indicate that the registration links will be available when we are closer to the event. Also, the Tokyo date is only listed on the NLS page because there is not a DYLC in Tokyo.

**Comment by blove** [comment]
Ok, thanks @InfamousStarFox.

**Pull request merged**
