### PR TITLE
DSA, Urner Goodman Camping, & Josh Sain award page created

### PR DESCRIPTION
**Pull request by InfamousStarFox**
Created the awards page, DSA, Urner Goodman Camping, & Josh Sain award
sub-pages

### CODE REVIEW

**Comment by blove** [comment]
@InfamousStarFox I think we want to put the awards Sass code in it's own .scss file. So, create the file in _sass/pages/program/awards/_index.scss and then include this at the bottom of the css/main.scss file where we import the pages.

**Comment by blove** [comment]
@InfamousStarFox Can you update the resources/maps/index.html file to use the updated links to the map files? It looks like they are still using the old /downloads folder.

**Comment by InfamousStarFox** [comment]
@blove  Yes, that has been fixed in my most recent pull request in addition to adding map links to the section pages

**Comment by blove** [comment]
@InfamousStarFox I'm still seeing the old links here: https://github.com/InfamousStarFox/western.oa-bsa.org/blob/e2df7259e5616ea1d5eb27670415f8d6ced35552/resources/maps/index.html

Am I missing something?

**Comment by InfamousStarFox** [comment]
@blove I can't submit a new pull request until the current request is closed. Once pull #7 is completed I can start pull #8 which fixes the links

**Comment by blove** [comment]
@InfamousStarFox Ok, I'll merge this pull request now.

**Pull request merged**
