### PR TITLE
Post Pictures

### PR DESCRIPTION
**Pull request by MacRichards**
Added and fixed pictures to posts and fixed the map post.

### CODE REVIEW

**Comment by InfamousStarFox** [comment]
Hey @MacRichards just looking at the first couple of changed files, it looks like you deleted the image tag instead of downloading the image and updating the link.
Here are some image links to help get you started:

 _posts/2007-02-11-049-2007-quality-lodge-award.markdown
http://western.oa-bsa.org/images/2006_ql_pin.jpg

 _posts/2007-09-23-054-summer-mustang-newsletter-available.markdown
http://western.oa-bsa.org/images/mustang2007summer.jpg

posts/2007-11-09-055-2008-quality-lodge-planbook-and-pocketbook.markdown
http://western.oa-bsa.org/images/2007_ql_pb.gif

_posts/2007-11-20-056-fall-mustang-newsletter-available.markdown
http://western.oa-bsa.org/images/mustang2007fall.jpg

_posts/2009-11-14-098-2010-philmont-oa-adviser-training-conference.markdown
http://western.oa-bsa.org/images/philmont.jpg

**Comment by MacRichards** [comment]
@InfamousStarFox I did just delete the image tag for the posts in 2007 because I didn't have access to view the posts on the live website and I didn't think anyone would really care since they are 9 years old now. Some other posts I just deleted the image tag because It wasn't on the live website.

**Comment by blove** [comment]
@InfamousStarFox can you pull images for @MacRichards from the FTP site?

**Comment by blove** [comment]
@InfamousStarFox and @MacRichards - should we just merge this pull request and then worry about the old posts later?

**Comment by MacRichards** [comment]
@blove that sounds good too me

**Comment by InfamousStarFox** [comment]
@blove I think so. It might also be worth considering just archiving some of the really old posts too.

**Comment by blove** [comment]
@InfamousStarFox right - we could just remove the files. Let's leave them for now, and I'll get some more input on this.

**Pull request merged**
