### PR TITLE
Updated Maps Links

### PR DESCRIPTION
**Pull request by InfamousStarFox**

### CODE REVIEW

**Comment by blove** [comment]
@InfamousStarFox Please change the leading slash ( / ) with {{ site.baseurl }} in the href attributes.

**Comment by InfamousStarFox** [comment]
@blove Do you know of a way to edit this in the existing pull request (#8) or do I have to issue a new pull request?

**Comment by bbodenmiller** [comment]
@InfamousStarFox you can just create another commit on this branch to update the pull request.

**Comment by InfamousStarFox** [comment]
@blove The changes have been made

**Comment by blove** [comment]
@InfamousStarFox Thanks!

**Pull request merged**
