### PR TITLE
Mobile Navigation

### PR DESCRIPTION
**Pull request by InfamousStarFox**
Mobile navigation menu added, and general CSS improvements

### CODE REVIEW

**Comment by blove** [comment]
@InfamousStarFox can you update your changes to the _navbar.scss file to use Sass instead of CSS. In other words, this:

`.sidenav a {`

should be:

`.sidenav
 {
  ...
  a {
    ...
   &:hover {
      ...
    }
  }
}`

**Comment by InfamousStarFox** [comment]
Alright, I have updated it

**Comment by blove** [comment]
Thanks!

Also, I don't think you need to explicitly set the background-size property as the retina-image mixin from the Bourbon library should be doing this for you. You can see the docs on this at:

http://bourbon.io/docs/#retina-image

**Comment by blove** [comment]
Just to note this, if we do need the background-size property to be set we should ideally not specify the vendor prefix versions (e.g. -webkit-background-size) in our Sass code. Rather, we should be using a library like postcss to do this for us based on our browser targets (and caniuse.com):

https://github.com/postcss/postcss

**Comment by InfamousStarFox** [comment]
The background-size is needed for the image to display correctly on ultra-wide screen (panoramic) monitors.

PostCSS appears to be a bit heavier of a solution than is necessary because all modern browsers (including mobile browsers) support the background-size property without the need for vendor specific prefix versions such as -webkit-background-size or -moz-background-size

The additional prefixes are there just in case someone just so happens to be using an ultra-wide screen monitor on Google Chrome 4.0, IE 9.0, Firefox 4.0, Safari 4.1, or Opera 10.5

**Comment by blove** [comment]
As per our conversation, we will keep the background-size property for non-retina (high density) displays. And, using the postcss library is beyond our needs at this time.

**Pull request merged**
