### PR TITLE
Crater Lake Post

### PR DESCRIPTION
**Pull request by MacRichards**
Crated the Crater Lake post and added Eric Wagstaff to the author.yml

### CODE REVIEW

**Comment by blove** [comment]
@MacRichards it looks like you create an authors.yml file in the webroot. This is already located in the _data directory. Can you remove that and commit again?

**Comment by MacRichards** [comment]
Yes I can. I don't know why those commits showed up.

**Comment by blove** [comment]
It looks like a copy of the article .markdown file was also committed to the root.

**Comment by MacRichards** [comment]
Yeah I know what happened. I'll fix it when I get home in an hour

**Comment by MacRichards** [comment]
@blove I'm going to be unable to do anything to fix this pull request for a couple days most likely. Due to a major storm going over my area we have lost power and have no idea when it will come back.

**Pull request closed without merging**
