### PR TITLE
Committee Portal Created

### PR DESCRIPTION
**Pull request by InfamousStarFox**
Page with an iframe linking to the php page for the committee members

### CODE REVIEW

**Comment by blove** [comment]
@InfamousStarFox A couple of changes:
1. The Sass code should go in appropriate files under _sass/pages/ to match the location of the page. For the /committee/index.html file there should a matching _sass/pages/committee/index.scss file. This enforces a convention so that it is easy to find the Sass code for page in the future. I would not know to look for this in the _banners.scss file.
2. The /adviser folder should be renamed to "advisers" to match the current URL on the website.
3. The /adviser/index.html file should use a separate class from the committee class to eliminate the dependency that should not exist.
4. I don't think you need the text within the iframe element. It is well supported by all browsers.

**Comment by InfamousStarFox** [comment]
@blove I have made changes 1-3. However I believe an error message should be left in the event of an iframe not loading; just in case a committee member is using an older web browser, or a light weight browser like the Amazon Kindle's browser.

**Comment by blove** [comment]
Can you create an advisor/index.scss file for the advisor page, move the sass code out of the committee/index.scss file, and include this new file in main?

**Comment by blove** [comment]
@InfamousStarFox can you rename "TechTeam" to be lower dashed case: "tech-team"?

**Pull request merged**
